/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  NormDspList as NormDspList
} from './components/norm-dsp-list/norm-dsp-list';

declare global {
  interface HTMLNormDspListElement extends NormDspList, HTMLElement {
  }
  var HTMLNormDspListElement: {
    prototype: HTMLNormDspListElement;
    new (): HTMLNormDspListElement;
  };
  interface HTMLElementTagNameMap {
    "norm-dsp-list": HTMLNormDspListElement;
  }
  interface ElementTagNameMap {
    "norm-dsp-list": HTMLNormDspListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "norm-dsp-list": JSXElements.NormDspListAttributes;
    }
  }
  namespace JSXElements {
    export interface NormDspListAttributes extends HTMLAttributes {
      propdata?: any;
      name?: any;
    }
  }
}

